steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/nexastore-app:$COMMIT_SHA','-t','gcr.io/$PROJECT_ID/nexastore-app:latest','-f','backend/Dockerfile','./backend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/nexastore-app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/nexastore-app:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - nexastore-app
      - --image=gcr.io/$PROJECT_ID/nexastore-app:$COMMIT_SHA
      - --region=europe-north1
      - --platform=managed
      - --port=8080
      - --vpc-connector=svpc-eun1
      - --vpc-egress=private-ranges-only
      - --set-secrets=DATABASE_URL=DATABASE_URL:latest
      - --set-env-vars=PORT=8080,NODE_ENV=production
      - --allow-unauthenticated
      - --min-instances=0
      - --max-instances=10
      - --memory=512Mi
      - --cpu=1

substitutions:
  _REGION: 'europe-north1'
  _SERVICE_NAME: 'nexastore-app'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
